services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=1
    volumes:
      - ./:/app
      - sqlite_data:/app/data
      - ../sotero_map/src/data:/app/frontend-data:ro
      - "C:/Users/paolo.vilches/Downloads:/app/import:ro"
