services:
  api:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Data Source=/app/data/soteromap.db
      - AllowedOrigins=http://localhost:3000,http://localhost:8080
      - FrontendDataRoot=/app/frontend-data
      - ExcelImportPath=/app/import/Inventario tns 2026.xlsx
      - SeedUsers__Admin__Username=${SEED_ADMIN_USERNAME}
      - SeedUsers__Admin__Password=${SEED_ADMIN_PASSWORD}
      - SeedUsers__Viewer__Username=${SEED_VIEWER_USERNAME}
      - SeedUsers__Viewer__Password=${SEED_VIEWER_PASSWORD}
    volumes:
      - sqlite_data:/app/data   # persiste el archivo .db entre reinicios
      - ../sotero_map/src/data:/app/frontend-data:ro
      - "C:/Users/paolo.vilches/Downloads/Inventario tns 2026.xlsx:/app/import/Inventario tns 2026.xlsx:ro"
    restart: unless-stopped

volumes:
  sqlite_data:
