FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN sed -i 's|http://deb.debian.org|https://deb.debian.org|g' /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && apt-get install -y --no-install-recommends libreoffice-writer fonts-dejavu-core fonts-liberation2 fonts-crosextra-carlito fonts-crosextra-caladea \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/SoteroMap.API

ENV ASPNETCORE_URLS=http://0.0.0.0:8080
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=1

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "--project", "/app/SoteroMap.API/SoteroMap.API.csproj", "run", "--", "--urls", "http://0.0.0.0:8080", "--contentRoot", "/app/SoteroMap.API"]
